### ISSUE TITLE
RATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTT

### ISSUE THREAD

**Issue by P80DISCORD** [CozzyBro2/World-Of-Fortnite#1]
RATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTTRATTTTTTTTTTTTTTTTTT

**Comment by CozzyBro2** [comment]
avg github user

**Comment by NotSoClassy** [comment]
he do be speaking fax tho
